FROM python:3.9-slim AS compile-image

WORKDIR /app

COPY requirements.txt .

RUN pip install --prefix=/install -r requirements.txt


FROM python:3.9

WORKDIR /app

COPY ./main.py /app/

COPY ./model_storage /app/model_storage

COPY ./model /app/model

COPY ./preprocess /app/preprocess

COPY ./phobert-base-v2 /app/phobert-base-v2

COPY --from=compile-image /install /usr/local

EXPOSE 30000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "30000"]